version: "3.9"
services:
# PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres-database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - go-postgres-network

# Golang App
  app:
    image: rahmaninsani/go-echo-clean-arch:v1 # comment this if you use local project
    container_name: go-echo
    #build: . # uncomment this if you use local project
    ports:
      - '8080:8080'
    restart: on-failure
    volumes:
      - golang-data:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - go-postgres-network

# Volumes
volumes:
  postgres-data:
  golang-data:

# Network
networks:
  go-postgres-network:
    driver: bridge
